name: Build and Test C++ Project

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Bazelisk
      run: |
        # Install Bazelisk
        curl -Lo bazel https://github.com/bazelbuild/bazelisk/releases/latest/download/bazelisk-linux-amd64
        chmod +x bazel
        mv bazel "$HOME/bin/"
        export PATH="$HOME/bin:$PATH"
        bazel --version

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++

    - name: Build and Test
      run: |
        ./tools/build.sh
